using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProClubsPlayerFinder.API.Migrations
{
    /// <inheritdoc />
    public partial class AddedClubsWithClubIdAutoGenerated : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ClubId",
                table: "AspNetUsers",
                type: "int",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "Clubs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OwnerPlayerId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: true),
                    ClubName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Console = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK__Clubs__D35058E7947E6D35", x => x.Id);
                    table.ForeignKey(
                        name: "FK__Clubs__OwnerPlay__52593CB8",
                        column: x => x.OwnerPlayerId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "2ec68e2f-fa24-4abf-8bdf-d82f530adee0",
                columns: new[] { "ClubId", "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { null, "eb8611d0-89a4-43f2-9a8a-2d2f12dc00fc", "AQAAAAIAAYagAAAAEPErjwNr8OIKHtid7DNn+OCPSrCwJnSw9vJw1omvnUYtfcPsO7F/i/IY/MV2mW6+PA==", "851d1cc2-ed7a-4332-93ee-08637fed06a9" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "71a8b6ac-6395-41d8-94d4-e103350110c0",
                columns: new[] { "ClubId", "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { null, "0f1a47ff-aadc-4960-8fdc-0284d6df09b9", "AQAAAAIAAYagAAAAEKx1xPVACj3XawLXuVmwfh7qx/yu4rX8ljI7rKiYzXgWzCdDIJL7JiPY5lJc0/qjOQ==", "63375f83-86dd-4032-8f77-e5aa0d984353" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "7b867b03-fd4a-4410-a9fd-abdc32bda959",
                columns: new[] { "ClubId", "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { null, "3a0e88bd-842f-4f16-99a2-4ff8ce726e70", "AQAAAAIAAYagAAAAED8cc4kBG4TyI8y5BcAtbL75Unsdg5l/P4fYkasM/30RTLcUHYIJrRDDHLL3XwTXRg==", "17e95833-d5ac-4a48-ac36-f1599a3db5ae" });

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUsers_ClubId",
                table: "AspNetUsers",
                column: "ClubId");

            migrationBuilder.CreateIndex(
                name: "IX_Clubs_OwnerPlayerId",
                table: "Clubs",
                column: "OwnerPlayerId",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Players_Clubs",
                table: "AspNetUsers",
                column: "ClubId",
                principalTable: "Clubs",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Players_Clubs",
                table: "AspNetUsers");

            migrationBuilder.DropTable(
                name: "Clubs");

            migrationBuilder.DropIndex(
                name: "IX_AspNetUsers_ClubId",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "ClubId",
                table: "AspNetUsers");

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "2ec68e2f-fa24-4abf-8bdf-d82f530adee0",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "b44f931a-5605-452a-85b8-2b86160d9a99", "AQAAAAIAAYagAAAAEJIz5ZQlCwmp5aQmOh8DJYw+ZaSdL024tKahWOKy00IeRDnlSQvodPLVA1fG6xmiPg==", "b110c464-d663-4909-a9e7-08dc81329c77" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "71a8b6ac-6395-41d8-94d4-e103350110c0",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "3222a14e-26cd-4431-bac5-5b100812f020", "AQAAAAIAAYagAAAAEBrlGXcUQPhYRbhtczbip4zjwjSEs/24kvrc7g69+N10fNX5PNB+lK9HVrvuA30rlQ==", "b3c2b730-302f-4ee9-ac71-10c1f5e4c61d" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "7b867b03-fd4a-4410-a9fd-abdc32bda959",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "a19aa28c-90d1-4f6e-9516-68f582473db7", "AQAAAAIAAYagAAAAEAeSpvTiuUU7/v0VL306k6tRwjVc7rFtPUi/FxzOVv5BUDst+N5c0hNAbogrgSX4Yg==", "cb950bad-a128-4eed-b872-7089d25124f8" });
        }
    }
}
